services:
  postgres:
    image: postgres:alpine
    container_name: gonote-postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: gonote-redis
    ports:
      - ${REDIS_PORT:-6379}:6379  
    env_file:
      - .env