spring:
  application:
    name: @project.artifactId@
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:gonote}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

gonote:
  jwt:
    audience: ${JWT_AUDIENCE:gonote}
    public-key:
      path: ${JWT_PUBLIC_KEY_PATH:file:.keys/public.pem}
    private-key:
      path: ${JWT_PRIVATE_KEY_PATH:file:.keys/private.pem}
    access-token:
      lifespan: ${JWT_ACCESS_TOKEN_LIFESPAN:15m}
    refresh-token:
      lifespan: ${JWT_REFRESH_TOKEN_LIFESPAN:1d}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:*}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    